### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by thomgb** [typemytype/tracerRoboFontExtension#2]
In Sierra it worked, in El Capitan & Yosemite I have this error. 
Any suggestions..? :)

``` python
Traceback (most recent call last):
  File "tracer.py", line 493, in <module>
  File "lib/scripting/nameSpaceCallbacks.pyc", line 206, in OpenWindow
  File "tracer.py", line 408, in __init__
  File "tracer.py", line 426, in makePreview
  File "tracer.py", line 346, in traceImage
  File "mojo/compile.pyc", line 99, in executeCommand
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontCompiler/tools/compileTools.py", line 325, in _executeCommand
  File "subprocess.pyc", line 522, in call
  File "subprocess.pyc", line 710, in __init__
  File "subprocess.pyc", line 1335, in _execute_child
OSError: [Errno 13] Permission denied
```

**Comment by frankrolf** [comment]
Seems to work fo me today (High Sierra in RF3).

**Comment by typemytype** [comment]
mmm, this is the latest version?

its not on the latest RoboFont...

**Comment by typemytype** [comment]
and the current version is RoboFont 3...

the problem is that the embedded binaries are not executable
while loading the extension Tracer set the chmod see https://github.com/typemytype/tracerRoboFontExtension/blob/master/Tracer.roboFontExt/lib/tracer.py#L32-L33

hope this helps...
